[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM5
build_flags =
    -D ENABLE_AP_MODE
    -D ARDUINO_ARCH_ESP32
    -Iinclude
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/tzapu/WiFiManager.git
upload_protocol = esptool
